// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	NEXTJS_ENV: string;
	NEXT_PUBLIC_STRAPI_URL: string;
	ASSETS: Fetcher;
}
